encyclopedia/urls.py
from django.urls import path

from . import views

app_name= "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("random", views.random, name="random"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("wiki/<str:entry>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, QueryDict
from django.urls import reverse
from markdown2 import markdown
from random import choice
from typing import List

from . import util


def index(request : HttpRequest) -> HttpResponse:
    data : QueryDict = request.GET
    query = data.get('q')
    entries : List[str] = util.list_entries()
    if query:
        query_entries : list = list()
        for entry in entries:
            if query.lower() == entry.lower():
                return HttpResponseRedirect(reverse(f"encyclopedia:entry", args=(entry,)))
            elif query.lower() in entry.lower():
                query_entries.append(entry)
        return render(request, "encyclopedia/index.html", {
            "entries": query_entries,
            "query": True
        })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": entries,
            "query": False
        })

def entry(request : HttpRequest, entry : str) -> HttpResponse:
    exact_entry : str = util.get_exact_entry(entry)
    entries = util.list_entries()

    content : str = util.get_entry(exact_entry)
    if not content:
        return render(request, "encyclopedia/error.html")
    return render(request, "encyclopedia/entry.html", {
        'title': entry,
        'content': markdown(content)
    })

def create(request : HttpRequest) -> HttpResponse:
    if request.method == "POST":
        data : QueryDict = request.POST
        title : str = data.get('title')
        content : str = data.get('content')
        entries : list = util.list_entries()

        if not title or not content:
            return render(request, "encyclopedia/create.html", {
                "message": "Fill out data properly"
            })
        else:
            for entry in entries:
                if entry.lower() == title.lower():
                    return render(request, "encyclopedia/create.html", {
                        "message": "Title Already Taken"
                    })


            util.save_entry(title, content)
            return HttpResponseRedirect(reverse(f"encyclopedia:entry", args=(title,)))

    else:
        return render(request, "encyclopedia/create.html")

def random(request : HttpRequest) -> HttpResponse:
    entries = util.list_entries()
    entry = choice(entries)
    return HttpResponseRedirect(reverse(f"encyclopedia:entry", args=(entry,)))

def edit(request : HttpRequest, entry : str) -> HttpResponse:
    entry = util.get_exact_entry(entry)
    if request.method == "POST":
        data : QueryDict = request.POST
        content : str = data.get('content')
        if not content:
            return render(request, "encyclopedia/edit.html", {
                "message": "Fill out data properly",
                "title": entry,
                "content": util.get_entry(entry)
            })
        else:
            util.save_entry(entry, content)
            return HttpResponseRedirect(reverse(f"encyclopedia:entry", args=(entry,)))
        
    else:
        return render(request, "encyclopedia/edit.html", {
                "title": entry,
                "content": util.get_entry(entry)
            })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block body %}
    <form class="create-page-form" method="post">
        {% csrf_token %}
        <input required class="my-1" type="text" name="title" placeholder="Title" />
        <textarea required name="content" placeholder="Content"></textarea>
        <p class="text-center text-danger">{{ message }}</p>
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
    <h1 class="text-center">{{ title }}</h1>
    <form class="create-page-form" method="post">
        {% csrf_token %}
        <textarea required name="content">{{ content }}</textarea>
        <p class="text-center">{{ message }}</p>
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div class="btn-div">
        <a class="btn btn-primary edit-btn" href="{% url 'encyclopedia:edit' title %}">edit</a>
    </div>
    {{ content|safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h3 class="text-center">Error 404</h3>
    <h5 class="text-center">The page you search for doesn't exist</h5>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>
        {% if query %}
            Pages that match the query
        {% else %}
            All pages
        {% endif %}
    </h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="sidebar col-lg-2 col-md-3">
                    <h2>Wiki</h2>
                    <form>
                        <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    </form>
                    <div>
                        <a href="{% url 'encyclopedia:index' %}">Home</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                    </div>
                    {% block nav %}
                    {% endblock %}
                </div>
                <div class="main col-lg-10 col-md-9">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>